//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using Kinect = Windows.Kinect;


public class HeadTracker : MonoBehaviour
{
	public GameObject BodySourceManager;
	private BodySourceManager _BodyManager;
	
	void Update () 
	{
		if (BodySourceManager == null)
		{
			return;
		}
		
		_BodyManager = BodySourceManager.GetComponent<BodySourceManager>();
		if (_BodyManager == null)
		{
			return;
		}
		
		Kinect.Body[] data = _BodyManager.GetData();
		if (data == null)
		{
			return;
		}

		foreach(var body in data)
		{
			if (body == null)
			{
				continue;
			}
			
			if(body.IsTracked)
			{
				RefreshBodyObject(body);
			}
		}


	}
	
	private void RefreshBodyObject(Windows.Kinect.Body body)
	{

		Kinect.JointType jt = Kinect.JointType.Head;

		Kinect.Joint sourceJoint = body.Joints[jt];

		//set head/camera position on screen
		
		var headObjects = GameObject.FindGameObjectsWithTag("Head");
		var head = headObjects[0];

		head.transform.localPosition = GetVector3FromJoint(sourceJoint);

	}
	
	public static Vector3 GetVector3FromJoint(Kinect.Joint joint)
	{
		float x = joint.Position.X * 10;

		float z = joint.Position.Z * -5;

		float y = joint.Position.Y * 10;

		return new Vector3(x, y, z);
	}
}


